# Generated by Django 5.1.2 on 2024-11-17 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_alter_contact_address_alter_contact_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone_2',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone_3',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
